steps:
  checks:
    image: sinontm/ziglang:latest
    commands:
      - zig version
      - zig fmt --check .

  build:
    image: sinontm/ziglang:latest
    commands:
      - zig build

  behaviour-test:
    image: sinontm/ziglang:latest
    commands:
      - ./tests/test.sh zig-out/bin/scc ./tests/behaviour.txt

  nix:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix develop