steps:
  checks:
    image: sinontm/ziglang:v2
    commands:
      - zig version
      - zig fmt --check .

  build:
    image: sinontm/ziglang:v2
    commands:
      - zig build

  test:
    image: sinontm/ziglang:v2
    commands:
      - zig build test