steps:
  checks:
    image: sinontm/ziglang:latest
    commands:
      - zig version
      - zig fmt --check .

  build:
    image: sinontm/ziglang:latest
    commands:
      - zig build

  test:
    image: sinontm/ziglang:latest
    commands:
      - ./test.sh